# Generated by Django 4.2.6 on 2023-10-13 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobileNumber', models.PositiveBigIntegerField()),
                ('adhaar', models.PositiveBigIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apartmentName', models.CharField(max_length=255)),
                ('towerNo', models.PositiveIntegerField()),
                ('flatNumber', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='maids',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobileNumber', models.PositiveBigIntegerField()),
                ('adhaar', models.PositiveBigIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='maidsBank',
            fields=[
                ('bankName', models.CharField(max_length=255)),
                ('accountNumber', models.PositiveBigIntegerField()),
                ('accountName', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=15)),
                ('upiId', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maidsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maidcraft.maids')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='maidsAddress',
            fields=[
                ('doorNo', models.PositiveIntegerField()),
                ('pinCode', models.PositiveBigIntegerField()),
                ('area1', models.CharField(max_length=255)),
                ('area2', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maidsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maidcraft.maids')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customerBank',
            fields=[
                ('bankName', models.CharField(max_length=255)),
                ('accountNumber', models.PositiveBigIntegerField()),
                ('accountName', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=15)),
                ('upiId', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maidsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maidcraft.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customerAddress',
            fields=[
                ('doorNo', models.PositiveIntegerField()),
                ('pinCode', models.PositiveBigIntegerField()),
                ('area1', models.CharField(max_length=255)),
                ('area2', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maidcraft.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
